"""The cutout emitter: a rig document becomes a Godot scene that moves.

WHAT IT WRITES, and each file exists because the alternative is broken:

  <name>.tscn        the bone hierarchy as Node2Ds, one Sprite2D per filled
                     slot, an AnimationPlayer wired to the library below.
  <name>.anims.tres  an AnimationLibrary holding every clip, with the deltas
                     already baked onto this character's rest pose.

FIVE THINGS THIS FILE KNOWS THAT COST SOMETHING TO LEARN:

  1. +Y IS DOWN IN GODOT AND UP IN THE DOCUMENT. Every position and every
     rotation crosses that boundary exactly here, in `to_godot`. A flip applied
     in two places is a flip applied zero times, and a flip applied nowhere
     builds a character standing on its head who animates perfectly.

  2. TRACKS ARE BAKED, NOT LAYERED. The clips are authored as deltas from the
     TEMPLATE rest pose, and this adds `rest + adjustment + delta` at emit time.
     Writing the deltas straight out as absolute track values would erase every
     per-character adjustment on frame one of every clip — making "adjustments
     survive" a claim that is false the moment anything plays.

  3. z_as_relative = false, ON EVERY SPRITE. Godot 4's default is that a node's
     z_index is RELATIVE to its parent's, so a flat z table sums down the bone
     chain: the near arm at z 8 hangs off a chest whose chain already totals 12,
     and it draws in front of a head at z 9 that it should be behind. The
     document's z table is absolute and the scene has to say so.

  4. THE LIBRARY IS REGISTERED UNDER THE EMPTY NAME. `libraries = {"": ...}`.
     Register it as "lib" and every animation is addressed as "lib/idle", and
     `play("idle")` fails — silently, returning nothing, in a game that
     otherwise runs.

  5. METHOD CALLBACKS FIRE IMMEDIATELY. AnimationMixer's default is DEFERRED,
     which puts every animation event one frame late: a hitbox that opens after
     the swing has visually passed. `callback_mode_method = 1` is immediate.

AND IT REFUSES TO CLOBBER. A .tscn a human has opened in Godot is not ours to
overwrite; the emitter records the hash of what it wrote and will not replace a
file that no longer matches without an explicit force.
"""
from __future__ import annotations

import hashlib
import json
import math
import os
from pathlib import Path
from typing import Any, Optional

from . import cutout
from .cutout import CutoutError

HEADER = ("; GENERATED BY BUILDERS GATE — bgate cutout emitter. Edits here are "
          "lost on the next emit; change the .cutout.json and re-emit.\n"
          "; source: %s\n")

STAMP_SUFFIX = ".emit.json"


# ---------------------------------------------------------------------------
# The coordinate flip, in one place
# ---------------------------------------------------------------------------

def to_godot_pos(pos) -> tuple[float, float]:
    """Doc space (+y up) to Godot 2D (+y down)."""
    return (round(float(pos[0]), 4), round(-float(pos[1]), 4))


def to_godot_rot(degrees: float) -> float:
    """Degrees anticlockwise in doc space to radians clockwise in Godot.

    Same flip as the position and for the same reason: a screen whose y grows
    downward also measures its angles the other way round.
    """
    return round(math.radians(-float(degrees)), 6)


# ---------------------------------------------------------------------------
# Text helpers — a .tscn is a text format and this writes it directly
# ---------------------------------------------------------------------------

def _f(value) -> str:
    """A number that Godot's variant parser reads as a FLOAT, always.

    MEASURED, AND IT COST AN AFTERNOON. "%g" renders 0.0 as `0` and -0.0 as
    `-0`, which the .tres parser reads as INTEGERS. A value track whose keys are
    a mix of floats and ints does not error, does not warn, and does not apply:
    the clip plays, the playback position advances, method tracks on the same
    animation fire correctly, and the bone does not move a degree. The emitted
    walk cycle looked perfect in the file and was completely inert in the engine,
    and the only visible difference from a hand-built track that worked was
    `typeof(key) == TYPE_INT` on the keys that happened to be zero.
    """
    text = "%.6g" % float(value)
    if "." not in text and "e" not in text and "E" not in text:
        text += ".0"
    return text


def _vec2(pair) -> str:
    return f"Vector2({_f(pair[0])}, {_f(pair[1])})"


def _floats(values) -> str:
    # A PackedFloat32Array coerces its own contents, so ints are harmless
    # here — but rendering them consistently keeps a diff of two emits
    # readable, and there is no reason to have two number formats in one file.
    return "PackedFloat32Array(" + ", ".join(_f(v) for v in values) + ")"


def _res_path(project_dir: str | os.PathLike[str],
              path: str | os.PathLike[str]) -> str:
    """An absolute or project-relative path as a res:// path.

    Refuses anything outside the project rather than emitting a res:// path that
    will not resolve — which shows up as a scene full of missing textures with
    no explanation of where they went.
    """
    text = str(path).replace("\\", "/")
    if text.startswith("res://"):
        return text
    project = Path(project_dir).resolve()
    candidate = Path(path)
    if not candidate.is_absolute():
        candidate = project / candidate
    try:
        rel = candidate.resolve().relative_to(project)
    except ValueError:
        raise CutoutError(
            f"{candidate} is outside the Godot project at {project} — a "
            "cutout part has to live in the project to be loadable as "
            "res://") from None
    return "res://" + str(rel).replace("\\", "/")


# ---------------------------------------------------------------------------
# The animation library
# ---------------------------------------------------------------------------

def bake_clip(doc: dict, name: str) -> dict:
    """One clip's tracks, as ABSOLUTE Godot values for this character.

    Returns {name, length, loop_mode, tracks: [{path, property, keys}],
             events: [...]}. Keys are (time, value, transition).
    """
    spec = cutout.clip(name)
    rest = cutout.rest_pose(doc)
    tracks = []
    for bone, channels in (spec.get("tracks") or {}).items():
        if bone not in rest:
            # A clip authored for a template this character does not use. Say
            # so loudly: quietly dropping the track produces a walk cycle with
            # one leg.
            raise CutoutError(
                f"clip {name!r} animates bone {bone!r}, which is not in "
                f"{doc['template']!r}")
        path = cutout.bone_node_path(doc, bone)
        base = rest[bone]
        if channels.get("rot") is not None:
            keys = [(float(t), to_godot_rot(base["rot"] + float(d)))
                    for t, d in channels["rot"]]
            tracks.append({"path": f"{path}:rotation", "keys": keys,
                           "kind": "float"})
        if channels.get("pos") is not None:
            keys = []
            for t, delta in channels["pos"]:
                keys.append((float(t),
                             to_godot_pos([base["pos"][0] + float(delta[0]),
                                           base["pos"][1] + float(delta[1])])))
            tracks.append({"path": f"{path}:position", "keys": keys,
                           "kind": "vector2"})

    length = float(spec["length"])
    looping = bool(spec.get("loop")) and name not in cutout.NO_LOOP
    for track in tracks:
        if len(track["keys"]) > cutout.MAX_CLIP_KEYS:
            raise CutoutError(
                f"clip {name!r} track {track['path']} has "
                f"{len(track['keys'])} keys, over the "
                f"{cutout.MAX_CLIP_KEYS} ceiling")
        for time, _ in ((k[0], k[1]) for k in track["keys"]):
            if time > length + 1e-6:
                raise CutoutError(
                    f"clip {name!r} has a key at t={time} past its length "
                    f"{length}")
        # THE DOUBLE-HOLD. A looping clip whose last key sits exactly on the
        # length blends that pose into the identical first key, so the pose is
        # held for one extra frame every cycle and the loop visibly hitches.
        if looping and abs(track["keys"][-1][0] - length) < 1e-6:
            raise CutoutError(
                f"looping clip {name!r} has a key at exactly t == length on "
                f"{track['path']} — Godot blends the last key into the first, "
                "so that pose is held twice. Move the last key back one step.")
    return {"name": name, "length": length,
            "loop_mode": 1 if looping else 0,
            "tracks": tracks,
            "events": [list(e) for e in (spec.get("events") or [])],
            "fps": int(spec.get("fps") or 12)}


def library_text(doc: dict, clips: Optional[list] = None) -> str:
    """The AnimationLibrary .tres, with every clip baked for this character."""
    wanted = list(clips or cutout.clip_names())
    baked = [bake_clip(doc, name) for name in wanted]
    steps = len(baked) + 1
    out = [f"[gd_resource type=\"AnimationLibrary\" load_steps={steps} format=3]",
           "", HEADER % f"{doc['name']}{cutout.SUFFIX}"]
    for anim in baked:
        ident = f"Animation_{anim['name']}"
        out.append(f"[sub_resource type=\"Animation\" id=\"{ident}\"]")
        out.append(f"resource_name = \"{anim['name']}\"")
        out.append(f"length = {_f(anim['length'])}")
        out.append(f"loop_mode = {anim['loop_mode']}")
        index = 0
        for track in anim["tracks"]:
            times = [k[0] for k in track["keys"]]
            if track["kind"] == "vector2":
                values = "[" + ", ".join(_vec2(k[1]) for k in track["keys"]) + "]"
            else:
                # _f, not "%g" — see its docstring. A zero key rendered as an
                # int makes the whole track inert.
                values = "[" + ", ".join(_f(k[1]) for k in track["keys"]) + "]"
            out += [
                f"tracks/{index}/type = \"value\"",
                f"tracks/{index}/imported = false",
                f"tracks/{index}/enabled = true",
                f"tracks/{index}/path = NodePath(\"{track['path']}\")",
                # 1 = linear. The browser scrubber implements the same formula,
                # so preview and engine cannot disagree — which is the entire
                # reason an editor is worth having.
                f"tracks/{index}/interp = 1",
                f"tracks/{index}/loop_wrap = true",
                f"tracks/{index}/keys = {{",
                f"\"times\": {_floats(times)},",
                f"\"transitions\": {_floats([1.0] * len(times))},",
                "\"update\": 0,",
                f"\"values\": {values}",
                "}",
            ]
            index += 1
        for time, event in anim["events"]:
            out += [
                f"tracks/{index}/type = \"method\"",
                f"tracks/{index}/imported = false",
                f"tracks/{index}/enabled = true",
                # The METHOD track targets the rig root, which is where
                # cutout_rig.gd lives. "." is relative to the player's
                # root_node, which the scene pins to the rig root.
                f"tracks/{index}/path = NodePath(\".\")",
                f"tracks/{index}/interp = 1",
                f"tracks/{index}/loop_wrap = true",
                f"tracks/{index}/keys = {{",
                f"\"times\": {_floats([time])},",
                "\"transitions\": PackedFloat32Array(1),",
                "\"values\": [{",
                "\"args\": [\"" + str(event) + "\"],",
                "\"method\": &\"_anim_event\"",
                "}]",
                "}",
            ]
            index += 1
        out.append("")
    out.append("[resource]")
    out.append("_data = {")
    out.append(",\n".join(
        f"\"{a['name']}\": SubResource(\"Animation_{a['name']}\")"
        for a in baked))
    out.append("}")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# The scene
# ---------------------------------------------------------------------------

def scene_text(doc: dict, *, project_dir: str | os.PathLike[str],
               library_res: str, script_res: str,
               sizes: Optional[dict] = None) -> str:
    """The .tscn: bones as Node2Ds, filled slots as Sprite2Ds, one player.

    `sizes` maps slot -> (width, height) in pixels. Without it a sprite gets
    `centered = false` and NO offset, which puts the part's top-left on the
    joint — visibly wrong, but wrong in a way you can see and fix, which beats
    guessing a pivot offset from a size nobody measured.
    """
    doc = cutout.normalise(doc)
    rest = cutout.rest_pose(doc)
    sizes = sizes or {}
    skin = doc["skin"]

    textures = {}
    for slot, entry in skin.items():
        textures.setdefault(_res_path(project_dir, entry["texture"]), None)
    ext = {}
    lines_ext = []
    ident = 1
    lines_ext.append(
        f"[ext_resource type=\"Script\" uid=\"\" path=\"{script_res}\" id=\"1_rig\"]"
        .replace(" uid=\"\"", ""))
    lines_ext.append(
        f"[ext_resource type=\"AnimationLibrary\" path=\"{library_res}\" "
        f"id=\"2_lib\"]")
    for path in sorted(textures):
        ident += 1
        key = f"{ident + 1}_tex{ident}"
        ext[path] = key
        lines_ext.append(
            f"[ext_resource type=\"Texture2D\" path=\"{path}\" id=\"{key}\"]")

    body: list[str] = []
    body.append(f"[node name=\"{doc['name']}\" type=\"Node2D\"]")
    body.append("script = ExtResource(\"1_rig\")")
    # THE PIVOT TABLE TRAVELS WITH THE SCENE. equip() has to know where an
    # incoming texture hangs from, and baking one offset into the Sprite2D would
    # land every swapped part on the PREVIOUS part's pivot — the central feature
    # of a cutout rig, silently broken.
    pivots = {}
    for slot, entry in skin.items():
        pivots[_res_path(project_dir, entry["texture"])] = entry["pivot"]
    if pivots:
        body.append("part_pivots = {")
        body.append(",\n".join(f"\"{p}\": {_vec2([v[0], v[1]])}"
                               for p, v in sorted(pivots.items())))
        body.append("}")
    # AND THE TEXTURES ARE LISTED AS RESOURCES. Godot's exporter cannot see a
    # load() of a string built at runtime, so equipment textures referenced only
    # by path are stripped from an exported game and every swap fails there and
    # only there.
    if ext:
        body.append("equip_textures = [" + ", ".join(
            f"ExtResource(\"{key}\")" for _, key in sorted(ext.items())) + "]")
    body.append("")
    body.append("[node name=\"Visual\" type=\"Node2D\" parent=\".\"]")
    body.append("")

    # Bones, parents before children, so the .tscn's parent paths always exist.
    for bone in _hierarchy_order(doc):
        parent_path = _parent_path(doc, bone["name"])
        pos = to_godot_pos(rest[bone["name"]]["pos"])
        body.append(f"[node name=\"{bone['name']}\" type=\"Node2D\" "
                    f"parent=\"{parent_path}\"]")
        body.append(f"position = {_vec2(pos)}")
        rot = to_godot_rot(rest[bone["name"]]["rot"])
        if abs(rot) > 1e-9:
            body.append(f"rotation = {_f(rot)}")
        body.append("")

    for slot in doc["slots"]:
        entry = skin.get(slot["name"])
        if not entry:
            continue                      # an unfilled slot emits no node
        res = _res_path(project_dir, entry["texture"])
        bone_path = cutout.bone_node_path(doc, slot["bone"])
        body.append(f"[node name=\"{slot['name']}\" type=\"Sprite2D\" "
                    f"parent=\"{bone_path}\"]")
        body.append(f"texture = ExtResource(\"{ext[res]}\")")
        body.append("centered = false")
        size = sizes.get(slot["name"])
        if size:
            body.append("offset = " + _vec2([
                round(-entry["pivot"][0] * float(size[0]), 3),
                round(-(1.0 - entry["pivot"][1]) * float(size[1]), 3)]))
        body.append(f"z_index = {slot['z']}")
        # See the module note: Godot 4 z is parent-relative by default and a
        # flat table would sum down the chain.
        body.append("z_as_relative = false")
        if abs(entry["rot_offset"]) > 1e-9:
            body.append(f"rotation = {_f(to_godot_rot(entry['rot_offset']))}")
        if abs(entry["scale"] - 1.0) > 1e-9:
            body.append(f"scale = {_vec2([entry['scale'], entry['scale']])}")
        if entry.get("far_tint"):
            tint = entry["far_tint"]
            body.append("modulate = Color(%s)" % ", ".join(_f(c) for c in tint))
        body.append("")

    body.append("[node name=\"AnimationPlayer\" type=\"AnimationPlayer\" "
                "parent=\".\"]")
    body.append("libraries = {")
    body.append("\"\": ExtResource(\"2_lib\")")
    body.append("}")
    # Immediate, not deferred: see the module note on hitbox timing.
    body.append("callback_mode_method = 1")
    body.append("")

    steps = len(lines_ext) + 1
    head = [f"[gd_scene load_steps={steps} format=3]", ""]
    return "\n".join(head + lines_ext + [""] +
                     [HEADER % f"{doc['name']}{cutout.SUFFIX}"] + body) + "\n"


def _hierarchy_order(doc: dict) -> list[dict]:
    """Bones with every parent before its children."""
    by_name = {b["name"]: b for b in doc["bones"]}
    out, placed = [], set()
    remaining = list(doc["bones"])
    while remaining:
        progressed = False
        for bone in list(remaining):
            parent = bone["parent"]
            if not parent or parent in placed:
                out.append(bone)
                placed.add(bone["name"])
                remaining.remove(bone)
                progressed = True
        if not progressed:                # normalise() refuses cycles first
            raise CutoutError("bone hierarchy could not be ordered")
    return out


def _parent_path(doc: dict, bone: str) -> str:
    by_name = {b["name"]: b for b in doc["bones"]}
    parent = by_name[bone]["parent"]
    if not parent:
        return "Visual"
    return cutout.bone_node_path(doc, parent)


# ---------------------------------------------------------------------------
# Emitting to disk, without stepping on a human
# ---------------------------------------------------------------------------

def _digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def stamp_path(scene_path: str | os.PathLike[str]) -> Path:
    return Path(str(scene_path) + STAMP_SUFFIX)


def emit(doc: dict, *, project_dir: str | os.PathLike[str],
         scene_path: str | os.PathLike[str],
         script_res: str = "res://addons/bgate/cutout_rig.gd",
         clips: Optional[list] = None, sizes: Optional[dict] = None,
         force: bool = False) -> dict:
    """Write the scene and the library. Returns what it wrote and what it refused.

    BYTE-IDENTICAL FOR AN UNCHANGED DOCUMENT — of the emitter's own output. Godot
    rewrites uids and .import sidecars on disk when it opens the project, so the
    claim is scoped to the text this function produces and no further.
    """
    doc = cutout.normalise(doc)
    scene = Path(scene_path)
    library = scene.with_suffix("").with_suffix(".anims.tres")
    library_res = _res_path(project_dir, library)

    text_lib = library_text(doc, clips)
    text_scene = scene_text(doc, project_dir=project_dir,
                            library_res=library_res, script_res=script_res,
                            sizes=sizes)

    # A HUMAN'S EDITS ARE NOT OURS TO DISCARD. The stamp records what we last
    # wrote; a file on disk that no longer matches it was changed by someone,
    # and Godot itself changes scenes just by opening them.
    stamp = stamp_path(scene)
    previous = {}
    if stamp.is_file():
        try:
            previous = json.loads(stamp.read_text(encoding="utf-8"))
        except ValueError:
            previous = {}
    refused = []
    for path, text, key in ((scene, text_scene, "scene"),
                            (library, text_lib, "library")):
        if path.is_file() and previous.get(key) and not force:
            now = _digest(path.read_text(encoding="utf-8"))
            if now != previous[key]:
                refused.append({
                    "path": str(path), "kind": key,
                    "note": "this file has changed since the emitter last wrote "
                            "it — someone edited it, or Godot rewrote it on "
                            "open. Re-emit with force=True to discard those "
                            "changes."})
    if refused:
        return {"ok": False, "refused": refused, "scene": str(scene),
                "library": str(library)}

    scene.parent.mkdir(parents=True, exist_ok=True)
    scene.write_text(text_scene, encoding="utf-8")
    library.write_text(text_lib, encoding="utf-8")
    stamp.write_text(json.dumps({"scene": _digest(text_scene),
                                 "library": _digest(text_lib),
                                 "name": doc["name"],
                                 "template": doc["template"]}, indent=2),
                     encoding="utf-8")
    return {
        "ok": True,
        "scene": str(scene),
        "library": str(library),
        "scene_res": _res_path(project_dir, scene),
        "library_res": library_res,
        "clips": list(clips or cutout.clip_names()),
        "bones": len(doc["bones"]),
        "sprites": len(doc["skin"]),
        "unfilled": [s["name"] for s in doc["slots"] if s["name"] not in doc["skin"]],
        "bytes": {"scene": len(text_scene), "library": len(text_lib)},
    }
