/* GENERATED BY scripts/slice_floor_cast.py - DO NOT EDIT.
 *
 * How many frames each of the floor cast's animation strips actually
 * has. It is written by the slicer because the slicer is the only
 * thing that knows: the count is a property of the sheet that was
 * generated and installed, not a constant somebody chose.
 *
 * EVERY LOOPING STRIP IS EIGHT AND EVERY HANDOFF IS FOUR, and no two
 * frames of a strip are the same picture. That is a contract the
 * slicer holds to (TARGET_FRAMES) rather than a count that fell out
 * of what a provider sold: where fewer drawings exist than the
 * contract asks for, the frames between them are the neighbouring
 * drawing carrying the part of the motion that belongs at that phase
 * - a few pixels of chest for a breath, of bounce and lean for a
 * stride or a keystroke. Nothing here holds one drawing for two
 * frames, which is what the counts recorded before.
 *
 * The renderer reads it for two things that have to agree: the
 * background-size that lays the strip across the sprite box, and the
 * steps() count that walks it. Getting them from one number is what
 * stops a strip being stepped through at the wrong width. */
export const CAST_FRAMES: Record<string, Record<string, number>> = {
  art: { idle: 8, sitting: 8, walk: 8, working: 8, handoff: 4 },
  audio: { idle: 8, sitting: 8, walk: 8, working: 8, handoff: 4 },
  narrative: { idle: 8, sitting: 8, walk: 8, working: 8, handoff: 4 },
  gameplay: { idle: 8, sitting: 8, walk: 8, working: 8, handoff: 4 },
  qa: { idle: 8, sitting: 8, walk: 8, working: 8, handoff: 4 },
  cinematic: { idle: 8, sitting: 8, walk: 8, working: 8, handoff: 4 },
  tech: { idle: 8, sitting: 8, walk: 8, working: 8, handoff: 4 },
  director: { idle: 8, sitting: 8, walk: 8, working: 8, handoff: 4 },
  generic: { idle: 8, sitting: 8, walk: 8, working: 8, handoff: 4 },
};

/** How many frames <seat>'s <anim> strip has.
 *
 *  ONE for an unknown seat rather than zero: a project can invent a
 *  seat, it falls back to the `generic` drawing, and a zero here would
 *  divide the sprite box by nothing. */
export function castFrames(seat: string, anim: string): number {
  return CAST_FRAMES[seat]?.[anim] ?? 1;
}
