/* THE STUDIO'S SOUNDTRACK: chill lofi work tracks, cycled, never repeating
 * inside a session.
 *
 * WHERE THE TRACKS LIVE, WHICH THE PLAN LEFT OPEN AND THIS SETTLES. They are
 * HARNESS UI AUDIO, not game assets, so they must not go through
 * kie_music_generate -> music_keep -> music_install: that pipeline installs
 * under the ENGINE PROJECT, and a game would ship the dashboard's background
 * music in its own music library, where the next person to audit that folder
 * would find eight lofi tracks nobody wrote a cue for. They live beside the
 * floor's other art instead - frontend/public/audio/floor/, served at
 * /static/audio/floor/ - on exactly the same footing as the cast sprites:
 * generated by the harness, committed, reproducible from a script, and shipped
 * inside the wheel and the PyInstaller build with no CDN to reach for.
 *
 * THE MANIFEST IS A FILE, NOT AN ENDPOINT. A directory listing route would be a
 * server change for a folder whose contents change when somebody regenerates
 * the set, which is a build-time event; scripts/gen_floor_music.py writes
 * manifest.json in the same act that downloads the audio, so the list and the
 * files cannot disagree. A missing manifest is not an error - it means nobody
 * has generated the set yet, and the floor is simply silent.
 *
 * IT IS OFF UNTIL ASKED. A dashboard that starts playing music because a pane
 * came into view is hostile, and on a machine with a stream running it is worse
 * than hostile. The toggle survives a reload, like the banter mute, and the two
 * are deliberately separate controls: somebody may want the room to have a
 * soundtrack and no jokes, or the reverse.
 *
 * NO REPEAT WITHIN A SESSION is the whole reason there is a bag rather than an
 * index. A playlist that walks a fixed order is recognisable by the third loop
 * and a random pick repeats a track back to back roughly one time in eight. The
 * bag is shuffled, drained, and only refilled when it is empty - and the refill
 * never puts the track that just played at the front, so the seam between two
 * passes does not play the same file twice.
 */

import { useCallback, useEffect, useRef, useState } from "react";

const DIR = "/static/audio/floor";
const KEY = "bg4.floor.music";
const VOL_KEY = "bg4.floor.music.vol";

/** One generated track. Written by scripts/gen_floor_music.py; nothing in the
 *  app invents an entry, because an entry that names a file that is not there
 *  is a player that stalls with no way to see why. */
export type Track = {
  /** File name inside /static/audio/floor. */
  file: string;
  /** What the generator asked Suno for, kept so a set can be regenerated and so
   *  the reader of the manifest can tell two very similar tracks apart. */
  title: string;
  /** The genre bucket the brief asked for - the plan wants "several genres",
   *  and without this the set is eight variations on one prompt. */
  genre?: string;
  seconds?: number;
};

export type Manifest = { tracks: Track[] };

export function musicOnStored(): boolean {
  /* DEFAULT OFF, and that is the opposite of the banter default on purpose.
     A caption nobody reads costs nothing; audio starting by itself is a thing
     you have to go and stop. */
  try { return localStorage.getItem(KEY) === "1"; } catch { return false; }
}
export function storeMusicOn(on: boolean) {
  try { localStorage.setItem(KEY, on ? "1" : "0"); } catch { /* private mode */ }
}
function volStored(): number {
  try {
    const raw = Number(localStorage.getItem(VOL_KEY));
    return Number.isFinite(raw) && raw >= 0 && raw <= 1 ? raw : 0.35;
  } catch { return 0.35; }
}
function storeVol(v: number) {
  try { localStorage.setItem(VOL_KEY, String(v)); } catch { /* private mode */ }
}

/** Fisher-Yates. Written out rather than `sort(() => Math.random() - 0.5)`,
 *  which is not a shuffle - it biases heavily and the bias is invisible until
 *  somebody notices track three keeps coming up early. */
function shuffled<T>(items: readonly T[]): T[] {
  const out = items.slice();
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

export type MusicDeck = {
  /** Null until the manifest has been read. Empty array means read and there is
   *  no set generated, which is a different thing and the UI says so. */
  tracks: Track[] | null;
  on: boolean;
  toggle: () => void;
  /** What is audible right now, for the label. Null while off or between. */
  now: Track | null;
  skip: () => void;
  volume: number;
  setVolume: (v: number) => void;
  /** The manifest could not be read at all - a genuinely broken install rather
   *  than an ungenerated one. */
  error: string;
};

export function useFloorMusic(): MusicDeck {
  const [tracks, setTracks] = useState<Track[] | null>(null);
  const [error, setError] = useState("");
  const [on, setOn] = useState(musicOnStored);
  const [now, setNow] = useState<Track | null>(null);
  const [volume, setVol] = useState(volStored);

  const audio = useRef<HTMLAudioElement | null>(null);
  const bag = useRef<Track[]>([]);
  const last = useRef<string>("");

  /* THE MANIFEST IS READ ONCE. It is a build artifact - it changes when
     somebody regenerates the set, which cannot happen while the page is open. */
  useEffect(() => {
    let live = true;
    fetch(`${DIR}/manifest.json`)
      .then((r) => {
        /* A 404 IS THE ORDINARY CASE, NOT A FAILURE. Nobody has generated the
           set on this checkout yet, and saying "could not read the manifest"
           about it would send the reader looking for a bug. */
        if (r.status === 404) return { tracks: [] } as Manifest;
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json() as Promise<Manifest>;
      })
      .then((m) => { if (live) setTracks(Array.isArray(m.tracks) ? m.tracks : []); })
      .catch((e) => { if (live) { setError(String(e.message || e)); setTracks([]); } });
    return () => { live = false; };
  }, []);

  /** Draw the next track. The bag is refilled only when it runs dry, and the
   *  refill is re-shuffled if it would repeat the track that just finished. */
  const draw = useCallback((): Track | null => {
    const all = tracks || [];
    if (all.length === 0) return null;
    if (all.length === 1) return all[0];
    if (bag.current.length === 0) {
      let next = shuffled(all);
      /* THE SEAM BETWEEN TWO PASSES IS THE ONLY PLACE A REPEAT CAN HAPPEN, and
         it is worth one re-shuffle to close: a bag that ends on track 5 and
         refills starting on track 5 plays it twice in a row, which is the exact
         thing "no repeat within a session" was written to prevent. */
      for (let i = 0; i < 8 && next[0].file === last.current; i++) next = shuffled(all);
      bag.current = next;
    }
    return bag.current.shift() || null;
  }, [tracks]);

  /* ONE <audio> ELEMENT FOR THE LIFE OF THE PANE, created outside React's tree.
     A React-rendered <audio> would be torn down and rebuilt whenever the pane
     re-renders around it, and every rebuild restarts the track from zero. */
  useEffect(() => {
    const el = new Audio();
    el.preload = "auto";
    audio.current = el;
    return () => { el.pause(); el.src = ""; audio.current = null; };
  }, []);

  useEffect(() => {
    const el = audio.current;
    if (el) el.volume = volume;
  }, [volume]);

  /* PLAY, STOP, AND WHAT HAPPENS AT THE END OF A TRACK. `ended` draws the next
     one rather than looping the same file, which is the whole cycle. */
  useEffect(() => {
    const el = audio.current;
    if (!el) return;
    if (!on) {
      el.pause();
      setNow(null);
      return;
    }
    /* TWO DIFFERENT FAILURES WEAR THE SAME REJECTED PROMISE, and the first
       version of this treated both as "give up": a missing FILE and a refused
       PERMISSION. They need opposite answers. A manifest row whose mp3 was
       deleted must cost one track, not the whole soundtrack - otherwise one
       stale row turns the switch off the instant somebody presses it, and the
       control reads as broken with nothing on screen to say why. Autoplay
       policy is the one that genuinely cannot be worked around, so it is the
       only one that puts the switch back.

       `tries` bounds the walk. Without it a manifest listing nothing but dead
       files recurses through the bag forever at whatever rate the network
       returns 404s. */
    let tries = 0;
    const play = () => {
      const t = draw();
      if (!t) return;
      last.current = t.file;
      setNow(t);
      el.src = `${DIR}/${encodeURIComponent(t.file)}`;
      el.volume = volume;
      el.play().then(() => { tries = 0; }).catch((err: unknown) => {
        const name = (err as { name?: string })?.name || "";
        if (name === "NotAllowedError") {
          /* The browser will not play audio yet. The toggle IS a user gesture
             so this is rare, but when it happens the honest thing is a switch
             that says off, not one that says playing over silence. */
          setOn(false);
          storeMusicOn(false);
          setNow(null);
          return;
        }
        /* Anything else is this FILE, not the deck. Move on. */
        if (++tries <= (tracks?.length || 1)) play();
        else { setOn(false); storeMusicOn(false); setNow(null); }
      });
    };
    /* A file that 404s never rejects play() on every browser - some resolve the
       promise and then fire `error` on the element. Same treatment. */
    const onError = () => { if (++tries <= (tracks?.length || 1)) play(); };
    el.addEventListener("ended", play);
    el.addEventListener("error", onError);
    play();
    return () => {
      el.removeEventListener("ended", play);
      el.removeEventListener("error", onError);
    };
  // `volume` is applied by its own effect; re-running this on a slider drag
  // would restart the track under the reader's hand.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [on, draw]);

  const toggle = useCallback(() => {
    setOn((was) => { storeMusicOn(!was); return !was; });
  }, []);

  const skip = useCallback(() => {
    const el = audio.current;
    if (!el || !on) return;
    /* Dispatching the element's own `ended` is what the cycle already listens
       for, so skipping and finishing take exactly one code path. */
    el.dispatchEvent(new Event("ended"));
  }, [on]);

  const setVolume = useCallback((v: number) => {
    const clamped = Math.min(1, Math.max(0, v));
    setVol(clamped);
    storeVol(clamped);
  }, []);

  return { tracks, on, toggle, now, skip, volume, setVolume, error };
}
